name: "Announce New Release - Discord"
on:
  release:
    types:
      - "published"
jobs:
  main:
    name: "Main"
    uses: "hugoalh/hugoalh/.github/workflows/announce-new-release-discord.yml@main"
    with:
      name: "Send IFTTT Webhook (Deno)"
      color: "#000000"
      thumbnail: "https://static-00.iconduck.com/assets.00/deno-icon-256x256-aruys1fu.png"
      releases: |
        **- GitHub (& Changelog):** ${{github.event.release.html_url}}
        **- Deno Land:** https://deno.land/x/send-ifttt-webhook
    secrets:
      DISCORD_WEBHOOK: "${{secrets.DISCORD_HXHS_PROJECTNEWRELEASEANNOUNCER_WEBHOOK}}"
